export const paises = [
  { sigla: "ZA", pais: "África do Sul" },
  { sigla: "DE", pais: "Alemanha" },
  { sigla: "AD", pais: "Andorra" },
  { sigla: "AO", pais: "Angola" },
  { sigla: "AG", pais: "Antígua e Barbuda" },
  { sigla: "SA", pais: "Arábia Saudita" },
  { sigla: "DZ", pais: "Argélia" },
  { sigla: "AR", pais: "Argentina" },
  { sigla: "AM", pais: "Armênia" },
  { sigla: "AU", pais: "Austrália" },
  { sigla: "AT", pais: "Áustria" },
  { sigla: "AZ", pais: "Azerbaijão" },
  { sigla: "BS", pais: "Bahamas" },
  { sigla: "BD", pais: "Bangladesh" },
  { sigla: "BB", pais: "Barbados" },
  { sigla: "BH", pais: "Barein" },
  { sigla: "BY", pais: "Belarus" },
  { sigla: "BE", pais: "Bélgica" },
  { sigla: "BZ", pais: "Belize" },
  { sigla: "BJ", pais: "Benin" },
  { sigla: "BO", pais: "Bolívia" },
  { sigla: "BA", pais: "Bósnia e Herzegovina" },
  { sigla: "BW", pais: "Botsuana" },
  { sigla: "BR", pais: "Brasil" },
  { sigla: "BN", pais: "Brunei" },
  { sigla: "BG", pais: "Bulgária" },
  { sigla: "BF", pais: "Burkina Faso" },
  { sigla: "BI", pais: "Burundi" },
  { sigla: "BT", pais: "Butão" },
  { sigla: "CV", pais: "Cabo Verde" },
  { sigla: "CM", pais: "Camarões" },
  { sigla: "KH", pais: "Camboja" },
  { sigla: "CA", pais: "Canadá" },
  { sigla: "QA", pais: "Catar" },
  { sigla: "KZ", pais: "Cazaquistão" },
  { sigla: "TD", pais: "Chade" },
  { sigla: "CL", pais: "Chile" },
  { sigla: "CN", pais: "China" },
  { sigla: "CY", pais: "Chipre" },
  { sigla: "CO", pais: "Colômbia" },
  { sigla: "KM", pais: "Comores" },
  { sigla: "CG", pais: "Congo" },
  { sigla: "CI", pais: "Costa do Marfim" },
  { sigla: "CR", pais: "Costa Rica" },
  { sigla: "HR", pais: "Croácia" },
  { sigla: "CU", pais: "Cuba" },
  { sigla: "DK", pais: "Dinamarca" },
  { sigla: "DJ", pais: "Djibouti" },
  { sigla: "DM", pais: "Dominica" },
  { sigla: "EG", pais: "Egito" },
  { sigla: "SV", pais: "El Salvador" },
  { sigla: "AE", pais: "Emirados Árabes Unidos" },
  { sigla: "EC", pais: "Equador" },
  { sigla: "ER", pais: "Eritréia" },
  { sigla: "SK", pais: "Eslováquia" },
  { sigla: "SI", pais: "Eslovênia" },
  { sigla: "ES", pais: "Espanha" },
  { sigla: "US", pais: "Estados Unidos da América" },
  { sigla: "EE", pais: "Estônia" },
  { sigla: "SZ", pais: "Eswatini" },
  { sigla: "ET", pais: "Etiópia" },
  { sigla: "FJ", pais: "Fiji" },
  { sigla: "PH", pais: "Filipinas" },
  { sigla: "FI", pais: "Finlândia" },
  { sigla: "FR", pais: "França" },
  { sigla: "GA", pais: "Gabão" },
  { sigla: "GM", pais: "Gâmbia" },
  { sigla: "GH", pais: "Gana" },
  { sigla: "GE", pais: "Geórgia" },
  { sigla: "GD", pais: "Granada" },
  { sigla: "GR", pais: "Grécia" },
  { sigla: "GT", pais: "Guatemala" },
  { sigla: "GY", pais: "Guiana" },
  { sigla: "GN", pais: "Guiné" },
  { sigla: "GQ", pais: "Guiné Equatorial" },
  { sigla: "GW", pais: "Guiné-Bissau" },
  { sigla: "HT", pais: "Haiti" },
  { sigla: "HL", pais: "Holanda" },
  { sigla: "HN", pais: "Honduras" },
  { sigla: "HU", pais: "Hungria" },
  { sigla: "YE", pais: "Iêmen" },
  { sigla: "MH", pais: "Ilhas Marshall" },
  { sigla: "SB", pais: "Ilhas Salomão" },
  { sigla: "IN", pais: "Índia" },
  { sigla: "ID", pais: "Indonésia" },
  { sigla: "IR", pais: "Irã" },
  { sigla: "IQ", pais: "Iraque" },
  { sigla: "IE", pais: "Irlanda" },
  { sigla: "IS", pais: "Islândia" },
  { sigla: "IL", pais: "Israel" },
  { sigla: "IT", pais: "Itália" },
  { sigla: "JM", pais: "Jamaica" },
  { sigla: "JP", pais: "Japão" },
  { sigla: "JO", pais: "Jordânia" },
  { sigla: "KI", pais: "Kiribati" },
  { sigla: "KW", pais: "Kuwait" },
  { sigla: "LA", pais: "Laos" },
  { sigla: "LS", pais: "Lesoto" },
  { sigla: "LV", pais: "Letônia" },
  { sigla: "LB", pais: "Líbano" },
  { sigla: "LR", pais: "Libéria" },
  { sigla: "LY", pais: "Líbia" },
  { sigla: "LI", pais: "Liechtenstein" },
  { sigla: "LT", pais: "Lituânia" },
  { sigla: "LU", pais: "Luxemburgo" },
  { sigla: "MK", pais: "Macedônia do Norte" },
  { sigla: "MG", pais: "Madagáscar" },
  { sigla: "MY", pais: "Malásia" },
  { sigla: "MW", pais: "Malauí" },
  { sigla: "MV", pais: "Maldivas" },
  { sigla: "ML", pais: "Mali" },
  { sigla: "MT", pais: "Malta" },
  { sigla: "MA", pais: "Marrocos" },
  { sigla: "MU", pais: "Maurício" },
  { sigla: "MR", pais: "Mauritânia" },
  { sigla: "MX", pais: "México" },
  { sigla: "MM", pais: "Mianmar" },
  { sigla: "FM", pais: "Micronésia" },
  { sigla: "MZ", pais: "Moçambique" },
  { sigla: "MD", pais: "Moldávia" },
  { sigla: "MC", pais: "Mônaco" },
  { sigla: "MN", pais: "Mongólia" },
  { sigla: "ME", pais: "Montenegro" },
  { sigla: "NA", pais: "Namíbia" },
  { sigla: "NR", pais: "Nauru" },
  { sigla: "NP", pais: "Nepal" },
  { sigla: "NI", pais: "Nicarágua" },
  { sigla: "NE", pais: "Níger" },
  { sigla: "NG", pais: "Nigéria" },
  { sigla: "NO", pais: "Noruega" },
  { sigla: "NZ", pais: "Nova Zelândia" },
  { sigla: "OM", pais: "Omã" },
  { sigla: "PW", pais: "Palau" },
  { sigla: "PA", pais: "Panamá" },
  { sigla: "PG", pais: "Papua Nova Guiné" },
  { sigla: "PK", pais: "Paquistão" },
  { sigla: "PY", pais: "Paraguai" },
  { sigla: "PE", pais: "Peru" },
  { sigla: "PL", pais: "Polônia" },
  { sigla: "PT", pais: "Portugal" },
  { sigla: "KE", pais: "Quênia" },
  { sigla: "KG", pais: "Quirguistão" },
  { sigla: "GB", pais: "Reino Unido" },
  { sigla: "CF", pais: "República Centro Africana" },
  { sigla: "KR", pais: "República da Coréia" },
  { sigla: "CD", pais: "República Democrática do Congo" },
  { sigla: "DO", pais: "República Dominicana" },
  { sigla: "KP", pais: "República Popular Democrática da Coréia" },
  { sigla: "CZ", pais: "República Tcheca" },
  { sigla: "RO", pais: "Romênia" },
  { sigla: "RW", pais: "Ruanda" },
  { sigla: "RU", pais: "Rússia (Federação Russa)" },
  { sigla: "WS", pais: "Samoa" },
  { sigla: "SM", pais: "San Marino" },
  { sigla: "LC", pais: "Santa Lúcia" },
  { sigla: "KN", pais: "São Cristóvão e Nevis" },
  { sigla: "ST", pais: "São Tomé e Príncipe" },
  { sigla: "VC", pais: "São Vicente e Granadinas" },
  { sigla: "SC", pais: "Seichelles" },
  { sigla: "SN", pais: "Senegal" },
  { sigla: "SL", pais: "Serra Leoa" },
  { sigla: "RS", pais: "Sérvia" },
  { sigla: "SG", pais: "Singapura" },
  { sigla: "SY", pais: "Síria" },
  { sigla: "SO", pais: "Somália" },
  { sigla: "LK", pais: "Sri Lanka" },
  { sigla: "SD", pais: "Sudão" },
  { sigla: "SS", pais: "Sudão do Sul" },
  { sigla: "SE", pais: "Suécia" },
  { sigla: "CH", pais: "Suíça" },
  { sigla: "SR", pais: "Suriname" },
  { sigla: "TJ", pais: "Tadjiquistão" },
  { sigla: "TH", pais: "Tailândia" },
  { sigla: "TZ", pais: "Tanzânia" },
  { sigla: "TL", pais: "Timor Leste" },
  { sigla: "TG", pais: "Togo" },
  { sigla: "TO", pais: "Tonga" },
  { sigla: "TT", pais: "Trinidad e Tobago" },
  { sigla: "TN", pais: "Tunísia" },
  { sigla: "TM", pais: "Turcomenistão" },
  { sigla: "TR", pais: "Turquia" },
  { sigla: "TV", pais: "Tuvalu" },
  { sigla: "UA", pais: "Ucrânia" },
  { sigla: "UG", pais: "Uganda" },
  { sigla: "UY", pais: "Uruguai" },
  { sigla: "UZ", pais: "Uzbequistão" },
  { sigla: "VU", pais: "Vanuatu" },
  { sigla: "VE", pais: "Venezuela" },
  { sigla: "VN", pais: "Vietnã" },
  { sigla: "ZM", pais: "Zâmbia" },
  { sigla: "ZW", pais: "Zimbábue" },
];

export const assuntos = [
  { valor: "economia", nome: "Economia" },
  { valor: "indicadores-sociais", nome: "Indicadores sociais" },
  { valor: "meio-ambiente", nome: "Meio Ambiente" },
  { valor: "populacao", nome: "População" },
  { valor: "redes", nome: "Redes" },
  { valor: "saude", nome: "Saúde" },
];

export const detalhesAssunto = {
  economia: [
    { valor: "77818", nome: "Chegada de turistas" },
    { valor: "77819", nome: "Gastos públicos com educação" },
    { valor: "77820", nome: "Gastos públicos com saúde" },
    { valor: "77821", nome: "Investimentos em pesquisa e desenvolvimento" },
    {
      valor: "77822",
      nome: "Mulheres de 15 anos ou mais de idade economicamente ativas",
    },
    {
      valor: "77824",
      nome: "População de 15 anos ou mais de idade economicamente ativa",
    },
    { valor: "77825", nome: "Total de exportações" },
    { valor: "77826", nome: "Total de importações" },
    { valor: "77827", nome: "Total do PIB" },
  ],
  "indicadores-sociais": [
    { valor: "77830", nome: "Esperança de vida ao nascer" },
    { valor: "77831", nome: "Índice de desenvolvimento humano" },
    { valor: "77832", nome: "População com acesso à água potável" },
    { valor: "77833", nome: "População com acesso à rede sanitária" },
    {
      valor: "77835",
      nome: "Taxa bruta de matrículas para todos os níveis de ensino",
    },
    {
      valor: "77836",
      nome: "Taxa de alfabetização das pessoas de 15 anos ou mais de idade",
    },
  ],
  "meio-ambiente": [
    { valor: "77838", nome: "Áreas cultivadas" },
    { valor: "77839", nome: "Áreas de pastagens permanentes" },
    {
      valor: "77840",
      nome: "Áreas protegidas no total do território nacional",
    },
    { valor: "77841", nome: "Produção de gás natural" },
    { valor: "77842", nome: "Produção de petróleo" },
  ],
  populacao: [
    { valor: "77844", nome: "Densidade demográfica" },
    { valor: "77845", nome: "Homens" },
    { valor: "77846", nome: "Mulheres" },
    { valor: "77847", nome: "População residente em área rural" },
    { valor: "77848", nome: "População residente em área urbana" },
    { valor: "77849", nome: "População" },
    { valor: "77850", nome: "Taxa bruta de mortalidade" },
    { valor: "77851", nome: "Taxa bruta de natalidade" },
    { valor: "77852", nome: "Taxa média anual do crescimento da população" },
  ],
  redes: [
    { valor: "77854", nome: "Assinaturas de telefonia celular" },
    { valor: "77855", nome: "Assinaturas de telefonia fixa" },
    { valor: "77857", nome: "Indivíduos com acesso à internet" },
  ],
  saude: [
    { valor: "77829", nome: "Consumo calórico" },
    { valor: "77834", nome: "Incidência de subnutrição" },
  ],
};
